services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Blueways\BwIcons\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  cache.bwicons_conf:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'bwicons_conf' ]

  Blueways\BwIcons\Utility\HelperUtility:
    public: true
    arguments:
      $cache: '@cache.bwicons_conf'
