services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Blueways\BwIcons\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Blueways\BwIcons\EventListener\BeforeJavaScriptsRenderingEventListener:
    tags:
      - name: 'event.listener'
        identifier: 'blueways/bw-icons-before-javascripts-rendering'
